import { FriendActivityItem, Interest, ProfileStatus, SimUser } from "@/types";

export const INTERESTS: Interest[] = [
  "Gaming",
  "Music",
  "Basketball",
  "Sports",
  "Fashion",
  "Creators",
  "Movies",
  "School",
  "Chill",
  "Just Chatting",
];

export const PROFILE_STATUSES: ProfileStatus[] = [
  "🎧 Listening to music",
  "🎮 Gaming",
  "🏀 Looking for hoopers",
  "📚 Studying",
  "😴 AFK",
  "💙 Just chilling",
  "✨ Looking for new friends",
];

export const AVATAR_OPTIONS = [
  "/avatars/avatar-wave.svg",
  "/avatars/avatar-fade.svg",
  "/avatars/avatar-curls.svg",
  "/avatars/avatar-locs.svg",
  "/avatars/avatar-short.svg",
  "/avatars/avatar-bob.svg",
];

export const BANNER_OPTIONS = [
  "/banners/blue-waves.svg",
  "/banners/midnight-grid.svg",
  "/banners/electric-sky.svg",
  "/banners/stadium.svg",
  "/banners/creator-room.svg",
  "/banners/after-hours.svg",
  "/banners/ice-pulse.svg",
  "/banners/blueprint.svg",
  "/banners/ocean-glass.svg",
  "/banners/night-drive.svg",
];

export const SIM_USERS: SimUser[] = [
  {
    id: "u-zay",
    username: "ZayOnTop",
    displayName: "Zay Carter",
    ageBracket: "13-15",
    interests: ["Gaming", "Basketball", "Music", "Chill"],
    online: true,
    lastSeen: "Online now",
    status: "🎮 Gaming",
    statusLine: "Running 2K and listening to new drops.",
    bio: "Competitive until the game ends, chill right after. Always looking for a solid Rec squad.",
    personality: "Competitive, funny, and low-key",
    favoriteMusic: "Hurricane Wisdom · Lil Tecca",
    favoriteGame: "NBA 2K",
    favoriteSport: "Basketball",
    banner: "/banners/stadium.svg",
    avatar: { image: "/avatars/zay.svg", gradient: "from-sky-500 via-blue-700 to-slate-950" },
  },
  {
    id: "u-mia",
    username: "MiaCreates",
    displayName: "Mia Brooks",
    ageBracket: "13-15",
    interests: ["Creators", "Fashion", "Music", "Movies"],
    online: true,
    lastSeen: "Online now",
    status: "✨ Looking for new friends",
    statusLine: "Editing a new fit check.",
    bio: "I make edits, thrift way too much, and rate movie endings like it is a full-time job.",
    personality: "Creative, talkative, and curious",
    favoriteMusic: "SZA · PinkPantheress",
    favoriteGame: "The Sims 4",
    favoriteSport: "Volleyball",
    banner: "/banners/creator-room.svg",
    avatar: { image: "/avatars/mia.svg", gradient: "from-cyan-400 via-blue-600 to-slate-950" },
  },
  {
    id: "u-kai",
    username: "KaiBuckets",
    displayName: "Kai Monroe",
    ageBracket: "13-15",
    interests: ["Basketball", "Sports", "School", "Just Chatting"],
    online: true,
    lastSeen: "Online now",
    status: "🏀 Looking for hoopers",
    statusLine: "Point guard. Always down to talk ball.",
    bio: "Lefty guard, film watcher, and certified defender of pass-first point guards.",
    personality: "Focused, upbeat, and competitive",
    favoriteMusic: "Lil Baby · Rod Wave",
    favoriteGame: "NBA 2K",
    favoriteSport: "Basketball",
    banner: "/banners/stadium.svg",
    avatar: { image: "/avatars/kai.svg", gradient: "from-blue-400 via-cyan-700 to-blue-950" },
  },
  {
    id: "u-nova",
    username: "NovaPlays",
    displayName: "Nova Reed",
    ageBracket: "13-15",
    interests: ["Gaming", "Creators", "Movies", "Just Chatting"],
    online: false,
    lastSeen: "Last seen 18m ago",
    status: "😴 AFK",
    statusLine: "Horror games are undefeated.",
    bio: "I stream horror games, make chaotic thumbnails, and somehow always choose the wrong door.",
    personality: "Dry humor, calm, and observant",
    favoriteMusic: "Steve Lacy · Tyler, The Creator",
    favoriteGame: "Phasmophobia",
    favoriteSport: "Skateboarding",
    banner: "/banners/after-hours.svg",
    avatar: { image: "/avatars/nova.svg", gradient: "from-blue-500 via-slate-700 to-black" },
  },
  {
    id: "u-lex",
    username: "LexVibes",
    displayName: "Alexis Lane",
    ageBracket: "13-15",
    interests: ["Music", "Fashion", "Chill", "Just Chatting"],
    online: true,
    lastSeen: "Online now",
    status: "🎧 Listening to music",
    statusLine: "Good music, good energy, no weirdness.",
    bio: "Playlist maker, sneaker admirer, and the friend who always has a random story.",
    personality: "Easygoing, expressive, and friendly",
    favoriteMusic: "Brent Faiyaz · GloRilla",
    favoriteGame: "Fortnite",
    favoriteSport: "Track",
    banner: "/banners/electric-sky.svg",
    avatar: { image: "/avatars/lex.svg", gradient: "from-cyan-500 via-sky-700 to-slate-950" },
  },
  {
    id: "u-ace",
    username: "AceClips",
    displayName: "Ace Holloway",
    ageBracket: "13-15",
    interests: ["Gaming", "Creators", "Sports", "Music"],
    online: true,
    lastSeen: "Online now",
    status: "✨ Looking for new friends",
    statusLine: "Trying to hit 10K followers this year.",
    bio: "Short-form creator. I clip games, sports moments, and anything that makes the group chat laugh.",
    personality: "High-energy, ambitious, and funny",
    favoriteMusic: "Ken Carson · NLE Choppa",
    favoriteGame: "Fortnite",
    favoriteSport: "Football",
    banner: "/banners/creator-room.svg",
    avatar: { image: "/avatars/ace.svg", gradient: "from-indigo-500 via-blue-700 to-black" },
  },
  {
    id: "u-jules",
    username: "JulesAfterDark",
    displayName: "Jules Morgan",
    ageBracket: "16-17",
    interests: ["Music", "Movies", "Chill", "Just Chatting"],
    online: true,
    lastSeen: "Online now",
    status: "💙 Just chilling",
    statusLine: "Late-night playlists and movie takes.",
    bio: "I will absolutely send a seven-minute voice note explaining why the soundtrack carried the movie.",
    personality: "Thoughtful, witty, and relaxed",
    favoriteMusic: "Frank Ocean · Don Toliver",
    favoriteGame: "Life is Strange",
    favoriteSport: "Tennis",
    banner: "/banners/after-hours.svg",
    avatar: { image: "/avatars/jules.svg", gradient: "from-sky-400 via-indigo-700 to-slate-950" },
  },
  {
    id: "u-roman",
    username: "RomanRunsIt",
    displayName: "Roman Ellis",
    ageBracket: "16-17",
    interests: ["Sports", "Basketball", "Gaming", "School"],
    online: true,
    lastSeen: "Online now",
    status: "🏀 Looking for hoopers",
    statusLine: "Varsity guard. Ranked grinder.",
    bio: "Morning workouts, school, hoops, repeat. I still make time for ranked though.",
    personality: "Disciplined, competitive, and direct",
    favoriteMusic: "Future · Babyface Ray",
    favoriteGame: "Call of Duty",
    favoriteSport: "Basketball",
    banner: "/banners/stadium.svg",
    avatar: { image: "/avatars/roman.svg", gradient: "from-blue-500 via-blue-800 to-black" },
  },
  {
    id: "u-skye",
    username: "SkyeStudio",
    displayName: "Skye Bennett",
    ageBracket: "16-17",
    interests: ["Creators", "Fashion", "Music", "School"],
    online: false,
    lastSeen: "Last seen 1h ago",
    status: "📚 Studying",
    statusLine: "Designing, filming, and figuring it out.",
    bio: "Design student energy before I am even a design student. Camera roll is 80% mood boards.",
    personality: "Inventive, kind, and detail-oriented",
    favoriteMusic: "Doechii · Billie Eilish",
    favoriteGame: "Minecraft",
    favoriteSport: "Soccer",
    banner: "/banners/creator-room.svg",
    avatar: { image: "/avatars/skye.svg", gradient: "from-cyan-400 via-slate-700 to-slate-950" },
  },
  {
    id: "u-dev",
    username: "DevMode",
    displayName: "Devin Parker",
    ageBracket: "16-17",
    interests: ["Gaming", "Creators", "Movies", "Just Chatting"],
    online: true,
    lastSeen: "Online now",
    status: "🎮 Gaming",
    statusLine: "Building a game that may or may not work.",
    bio: "Game dev beginner, professional bug creator, and horror movie defender.",
    personality: "Nerdy, clever, and quietly funny",
    favoriteMusic: "Playboi Carti · Metro Boomin",
    favoriteGame: "Roblox Studio",
    favoriteSport: "Esports",
    banner: "/banners/midnight-grid.svg",
    avatar: { image: "/avatars/dev.svg", gradient: "from-blue-600 via-cyan-800 to-black" },
  },
  {
    id: "u-riri",
    username: "RiriReplay",
    displayName: "Riley James",
    ageBracket: "16-17",
    interests: ["Music", "Fashion", "Creators", "Chill"],
    online: true,
    lastSeen: "Online now",
    status: "🎧 Listening to music",
    statusLine: "Concert clips and elite outfit opinions.",
    bio: "I film everything, remember every lyric, and will help plan the fit before the function.",
    personality: "Confident, social, and spontaneous",
    favoriteMusic: "Rihanna · Travis Scott",
    favoriteGame: "Just Dance",
    favoriteSport: "Cheer",
    banner: "/banners/electric-sky.svg",
    avatar: { image: "/avatars/riri.svg", gradient: "from-sky-500 via-blue-700 to-slate-950" },
  },
  {
    id: "u-eli",
    username: "EliTalks",
    displayName: "Eli Woods",
    ageBracket: "16-17",
    interests: ["Sports", "Movies", "School", "Just Chatting"],
    online: true,
    lastSeen: "Online now",
    status: "✨ Looking for new friends",
    statusLine: "Debates, sports, and random conversations.",
    bio: "I can turn almost any topic into a debate, but it stays friendly. Usually.",
    personality: "Outgoing, curious, and opinionated",
    favoriteMusic: "J. Cole · Kendrick Lamar",
    favoriteGame: "Madden NFL",
    favoriteSport: "Football",
    banner: "/banners/blue-waves.svg",
    avatar: { image: "/avatars/eli.svg", gradient: "from-indigo-400 via-sky-800 to-black" },
  },
];

export const COUNTRY_FILTERS = ["Random", "United States", "Canada", "United Kingdom", "Australia"];
export const LANGUAGE_FILTERS = ["Random", "English", "Spanish", "French", "Haitian Creole"];

export const TRENDING_INTERESTS = [
  { name: "Gaming", count: "4.8K talking" },
  { name: "Basketball", count: "3.2K matching" },
  { name: "Music", count: "6.1K vibing" },
  { name: "Creators", count: "2.7K posting" },
];

export const DAILY_MESSAGES = [
  "Good energy finds good energy. Show up as yourself today.",
  "The best VYBEs start with a real conversation—not a perfect first line.",
  "New friend potential: high. Weird energy tolerance: low.",
  "Today’s mission: meet somebody who puts you onto something new.",
];

export const FRIEND_ACTIVITY: FriendActivityItem[] = [
  { id: "activity-1", userId: "u-kai", text: "is looking for hoopers", createdAt: "4m" },
  { id: "activity-2", userId: "u-mia", text: "changed their status to Creating", createdAt: "12m" },
  { id: "activity-3", userId: "u-ace", text: "joined a Group Match", createdAt: "21m" },
];

export function getUserById(id: string) {
  return SIM_USERS.find((user) => user.id === id);
}
